    <section class="page-title">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <h1>FAQ </h1>
                </div>
            </div>
        </div>
    </section>

    <section class="main-containt">
        <div class="container">
            <div class="row">
                <h3><a class="anchor" name="general-questions" href="#general-questions"><i class="anchor-icon"></i></a>General Questions</h3>
                <h4><a class="anchor" name="q-what-is-telegram-what-do-i-do-here" href="#q-what-is-telegram-what-do-i-do-here"><i class="anchor-icon"></i></a>Q: What is Telegram? What do I do here?</h4>
                <p>Telegram is a messaging app with a focus on speed and security, it’s super-fast, simple and free. You can use Telegram on all your devices <strong>at the same time</strong> — your messages sync seamlessly across any number of your phones, tablets or computers.</p>
                <p>With Telegram, you can send messages, photos, videos and <a href="/blog/shared-files"><strong>files</strong></a> of any type (doc, zip, mp3, etc), as well as create groups for up to <strong>5000</strong> people or <a href="/blog/channels">channels</a> for broadcasting to <strong>unlimited</strong> audiences. You can write to your phone contacts and find people by their <a href="#usernames-and-telegram-me"><strong>usernames</strong></a>. As a result, Telegram is like SMS and email combined — and can take care of all your personal or business messaging needs.</p>
                <h4><a class="anchor" name="q-who-is-telegram-for" href="#q-who-is-telegram-for"><i class="anchor-icon"></i></a>Q: Who is Telegram for?</h4>
                <p>Telegram is for everyone who wants fast and reliable messaging. Business users and small teams may like the large groups, <a href="https://desktop.telegram.org">desktop apps</a> and powerful <a href="https://telegram.org/blog/shared-files">file sharing</a> options. Since Telegram groups can have up to <a href="/blog/supergroups5k">5000 members</a>, we support <a href="https://telegram.org/blog/replies-mentions-hashtags">replies, mentions and hashtags</a> that help maintain order and keep communication in large communities efficient.</p>
                <p>In case you&#39;re more into pictures, Telegram has animated <a href="/blog/gif-revolution">gif search</a>, a state of the art <a href="https://telegram.org/blog/photo-editor-and-passcodes">photo editor</a> and an <a href="/blog/stickers-revolution">open sticker platform</a> (find some cool stickers <a href="https://telegram.me/durov/40">here</a> or <a href="https://telegram.me/sticker">here</a>). What‘s more, there is no need to worry about disk space on your device. With Telegram’s cloud support and <a href="https://telegram.org/blog/cache-and-stickers">cache management options</a>,  Telegram can take up nearly <strong>zero</strong> space on your phone.</p>
                <p>Those looking for extra privacy should check out our <a href="/blog/privacy-revolution">advanced settings</a> and rather revolutionary <a href="/privacy">policy</a>. And if you want secrecy, try our device-specific <a href="#secret-chats">Secret Chats</a> with self-destructing messages, photos, and videos — and lock your app with an additional <a href="https://telegram.org/blog/photo-editor-and-passcodes">passcode</a>.</p>
                <blockquote>
                    <p>We keep evolving — check out the <a href="https://telegram.org/blog">blog</a> and follow us on <a href="https://twitter.com/telegram">twitter</a> to stay in touch.</p>
                </blockquote>
                <h4><a class="anchor" name="q-how-is-telegram-different-from-whatsapp" href="#q-how-is-telegram-different-from-whatsapp"><i class="anchor-icon"></i></a>Q: How is Telegram different from WhatsApp?</h4>
                <p>Unlike WhatsApp, Telegram is a cloud-based messenger with seamless sync. As a result, you can access your messages from several devices at once, including tablets and computers, and share an unlimited number of photos, videos and files (doc, zip, mp3, etc.) of up to 1,5 GB each. And if you don&#39;t want to store that data on your device, you can always <a href="https://telegram.org/blog/cache-and-stickers">keep it in the cloud</a>.</p>
                <p>Thanks to our multi-data center infrastructure and encryption, Telegram is faster and way more <a href="#security">secure</a>. On top of that, Telegram is free and will stay free — no ads, no subscription fees, forever.</p>
                <p>Our API is open, and we welcome developers to create their own Telegram apps. We also have a <a href="https://core.telegram.org/bots">Bot API</a>, a platform for developers that allows anyone to easily build specialized tools for Telegram. </p>
                <p>And that‘s just the tip of the iceberg. Don’t forget to check out <a href="#q-who-is-telegram-for">this paragraph</a> for even more exclusive stuff.</p>
                <h4><a class="anchor" name="q-how-old-is-telegram" href="#q-how-old-is-telegram"><i class="anchor-icon"></i></a>Q: How old is Telegram?</h4>
                <p>Telegram for iOS was launched on August 14, 2013. The alpha version of Telegram for Android officially launched on October 20, 2013. More and more <a href="/apps">Telegram clients</a> appear, built by independent developers using Telegram&#39;s <a href="//core.telegram.org/api">open platform</a>.</p>
                <h4><a class="anchor" name="q-which-devices-can-i-use" href="#q-which-devices-can-i-use"><i class="anchor-icon"></i></a>Q: Which devices can I use?</h4>
                <p>You can use Telegram on smartphones, tablets, and even computers. We have apps for <a href="https://telegram.org/dl/ios">iOS</a> (6 and above), <a href="https://telegram.org/dl/android">Android</a> (2.2 and up) and <a href="https://telegram.org/dl/wp">Windows Phone</a>. You can also use Telegram&#39;s <a href="https://web.telegram.org">web version</a> or install one of our <a href="https://desktop.telegram.org">desktop apps</a> for Windows, OSX, and Linux.</p>
                <blockquote>
                    <p>You can log in to Telegram from as many of your devices as you like — all <strong>at the same time</strong>. Just use your main mobile phone number to log in everywhere.</p>
                </blockquote>
                <p>Our <a href="//core.telegram.org/api">API</a> is open for developers, should you want to build your own applications for other platforms.  </p>
                <h4><a class="anchor" name="q-who-are-the-people-behind-telegram" href="#q-who-are-the-people-behind-telegram"><i class="anchor-icon"></i></a>Q: Who are the people behind Telegram?</h4>
                <p>Telegram is supported by Pavel and Nikolai Durov. Pavel supports Telegram financially and ideologically while Nikolai&#39;s input is technological. To make Telegram possible, Nikolai developed a unique custom data protocol, which is open, secure and optimized for work with multiple data-centers. As a result, Telegram combines security, reliability and speed on any network.</p>
                <p>While the Durov brothers were born in Russia, as were some of the key developers, Telegram is not connected to Russia – legally or physically. Telegram&#39;s HQ is in Berlin.</p>
                <blockquote>
                    <p>See also: <a href="/press">articles about Telegram</a></p>
                </blockquote>
                <h4><a class="anchor" name="q-will-you-have-ads-or-sell-my-data-or-steal-my-beloved-and-ensl" href="#q-will-you-have-ads-or-sell-my-data-or-steal-my-beloved-and-ensl"><i class="anchor-icon"></i></a>Q: Will you have ads? Or sell my data? Or steal my beloved and enslave my children?</h4>
                <p>No.</p>
                <h4><a class="anchor" name="q-how-are-you-going-to-make-money-out-of-this" href="#q-how-are-you-going-to-make-money-out-of-this"><i class="anchor-icon"></i></a>Q: How are you going to make money out of this?</h4>
                <p>We believe in fast and secure messaging that is also 100% free.</p>
                <p>Pavel Durov, who shares our vision, supplied Telegram with a generous donation through his Digital Fortress fund, so we have quite enough money for the time being. If Telegram runs out, we&#39;ll invite our users to donate and add non-essential paid options to break even. But making profits will never be a goal for Telegram. </p>
                <h4><a class="anchor" name="q-what-are-your-thoughts-on-internet-privacy" href="#q-what-are-your-thoughts-on-internet-privacy"><i class="anchor-icon"></i></a>Q: What are your thoughts on internet privacy?</h4>
                <p>Big internet companies like Facebook or Google have effectively hijacked the privacy discourse in the recent years. Their marketers managed to convince the public that the most important things about privacy are superficial tools that allow hiding your public posts or your profile pictures from the people around you. Adding these superficial tools enables companies to calm down the public and change nothing in how they are turning over private data to marketers and other third parties.</p>
                <p>At Telegram we think that the two most important components of Internet privacy should be instead:</p>
                <ol>
                    <li>Protecting your private conversations from snooping third parties, such as officials, employers, etc.</li>
                    <li>Protecting your personal data from third parties, such as marketers, advertisers, etc.</li>
                </ol>
                <p>This is what everybody should care about, and these are some of our top priorities. Telegram&#39;s aim is to create a truly free messenger, <a href="/privacy">without the usual caveats</a>. This means that instead of diverting public attention with low-impact settings, we can afford to focus on the real privacy issues that exist in the modern world.</p>
                <h4><a class="anchor" name="q-there-39s-illegal-content-on-telegram-how-do-i-take-it-down" href="#q-there-39s-illegal-content-on-telegram-how-do-i-take-it-down"><i class="anchor-icon"></i></a>Q: There&#39;s illegal content on Telegram. How do I take it down?</h4>
                <p>All Telegram chats and group chats are private amongst their participants. We do not process any requests related to them.</p>
                <p>But <strong>sticker sets</strong>, <strong>channels</strong>, and <strong>bots</strong> on Telegram are <em>publicly available</em>. If you find sticker sets or bots on Telegram that you think are illegal, please ping us at <a href="mailto:abuse@telegram.org">abuse@telegram.org</a></p>
                <h4><a class="anchor" name="q-a-bot-or-channel-is-infringing-on-my-copyright-what-do-i-do" href="#q-a-bot-or-channel-is-infringing-on-my-copyright-what-do-i-do"><i class="anchor-icon"></i></a>Q: A bot or channel is infringing on my copyright. What do I do?</h4>
                <p>All Telegram chats and group chats are private amongst their participants. We do not process any requests related to them. But <strong>sticker sets</strong>, <strong>channels</strong>, and <strong>bots</strong> on Telegram are <em>publicly available</em>.</p>
                <p>If you see a bot, channel, or sticker set that is infringing on your copyright, kindly submit a complaint to <a href="mailto:dmca@telegram.org">dmca@telegram.org</a>. Please note that such requests should only be submitted by the copyright owner or an agent authorized to act on the owner’s behalf.</p>
                <h4><a class="anchor" name="q-wait-0-o-do-you-process-take-down-requests-from-third-parties" href="#q-wait-0-o-do-you-process-take-down-requests-from-third-parties"><i class="anchor-icon"></i></a>Q: Wait! 0_o Do you process take-down requests from third parties?</h4>
                <p>Our mission is to provide a secure means of communication that work everywhere on the planet. To do that in the places where it is most needed (and to continue distributing Telegram through the App Store and Google Play), we have to process legitimate requests to take down illegal <strong>public</strong> content (sticker sets, bots, and channels) within the app. For example, we can take down sticker sets that violate intellectual property rights or porn bots.</p>
                <p>User-uploaded stickers sets, channels, and bots by third-party developers are not part of the core Telegram UI. Whenever we receive a complaint at <a href="mailto:abuse@telegram.org">abuse@telegram.org</a> or <a href="mailto:dmca@telegram.org">dmca@telegram.org</a> regarding the legality of public content, we perform the necessary legal checks and take it down when deemed appropriate.</p>
                <p>Please note that this does <strong>not</strong> apply to local restrictions on freedom of speech.  For example, if criticizing the government is illegal in some country, Telegram won‘t be a part of such politically motivated censorship. This goes against our founders’ <a href="http://mashable.com/2015/05/18/russias-mark-zuckerberg-pavel-durov/">principles</a>. While we do block terrorist (e.g. ISIS-related) bots and channels, we will not block anybody who peacefully expresses alternative opinions.</p>
                <h4><a class="anchor" name="q-my-bot-or-sticker-set-was-banned-unfairly-what-do-i-do" href="#q-my-bot-or-sticker-set-was-banned-unfairly-what-do-i-do"><i class="anchor-icon"></i></a>Q: My bot or sticker set was banned unfairly, what do I do?</h4>
                <p>If you think we banned your bot, channel, or sticker set for no apparent reasons, drop us a line at <a href="mailto:abuse@telegram.org">abuse@telegram.org</a>.</p>
                <h4><a class="anchor" name="q-do-you-process-data-requests" href="#q-do-you-process-data-requests"><i class="anchor-icon"></i></a>Q: Do you process data requests?</h4>
                <p>To protect the data that is not covered by end-to-end encryption, Telegram uses a distributed infrastructure. Cloud chat data is stored in multiple data centers around the globe that are controlled by different legal entities spread across different jurisdictions. The relevant decryption keys are split into parts and are never kept in the same place as the data they protect. As a result, several court orders from different jurisdictions are required to force us to give up any data.</p>
                <p>Thanks to this structure, we can ensure that no single government or block of like-minded countries can intrude on people&#39;s privacy and freedom of expression. Telegram can be forced to give up data only if an issue is grave and universal enough to pass the scrutiny of several different legal systems around the world.</p>
                <p>To this day, we have disclosed 0 bytes of user data to third parties, including governments.</p>
                <h3><a class="anchor" name="telegram-basics" href="#telegram-basics"><i class="anchor-icon"></i></a>Telegram Basics</h3>
                <h4><a class="anchor" name="q-who-can-i-write-to" href="#q-who-can-i-write-to"><i class="anchor-icon"></i></a>Q: Who can I write to?</h4>
                <p>You can write to people who are in your phone contacts and have Telegram.</p>
                <p>You can also select a public <a href="#usernames-and-telegram-me">username</a> for your Telegram account. Other people will be able to search and find you by that username — and send messages to you even if they don&#39;t know your number. You can learn more about usernames <a href="#usernames-and-telegram-me">here</a>.</p>
                <h4><a class="anchor" name="q-how-do-i-know-who-in-my-contacts-has-telegram" href="#q-how-do-i-know-who-in-my-contacts-has-telegram"><i class="anchor-icon"></i></a>Q: How do I know who in my contacts has Telegram?</h4>
                <p>Your contacts, who have Telegram, are shown at the top of your Contacts. They also have pictures.</p>
                <h4><a class="anchor" name="q-how-do-i-invite-my-friends" href="#q-how-do-i-invite-my-friends"><i class="anchor-icon"></i></a>Q: How do I invite my friends?</h4>
                <p><em>iOS:</em> The basic invitations are simple SMS messages. They will be charged as standard outgoing SMS by your carrier (unless sent via iMessage). Naturally, you have other options to bring your friends here. Try sending them a download link via any other messaging service: email, Facebook, WhatsApp, an actual telegram — you name it. The link: <a href="https://telegram.org/dl/"><strong><a href="https://telegram.org/dl/">https://telegram.org/dl/</a></strong></a></p>
                <p><em>Android:</em> Open the app menu (swipe right in chats list) — Invite Friends. Then choose an application via which you would like to send out invitations.</p>
                <p><em>Windows Phone:</em> Go to Contacts — Invite Friends. Then choose an application via which you would like to send out invitations.</p>
                <blockquote>
                    <p>You can give your friends a <a href="#q-how-does-telegram-me-work">telegram.me link</a> with your username so that they can easily find you on Telegram even if they don&#39;t have your phone number.</p>
                </blockquote>
                <h4><a class="anchor" name="q-what-do-the-green-checks-mean" href="#q-what-do-the-green-checks-mean"><i class="anchor-icon"></i></a>Q: What do the green checks mean?</h4>
                <p><em>One check</em> — message delivered to the Telegram cloud and your friend has been notified if he allows notifications.<br><em>Two checks</em> — message read (your friend opened Telegram and opened the conversation with the message).</p>
                <p>We don‘t have a ’delivered to device&#39; status for messages because Telegram can run on as many devices as you want. So which particular one would that check mean?</p>
                <h4><a class="anchor" name="q-can-i-hide-my-last-seen-time" href="#q-can-i-hide-my-last-seen-time"><i class="anchor-icon"></i></a>Q: Can I hide my ‘last seen’ time?</h4>
                <p>You can choose who sees this info in <a href="https://telegram.org/blog/privacy-revolution">Privacy and Security</a> settings.</p>
                <p>Remember that you won‘t see Last Seen timestamps for people with whom you don’t share your own. You will, however, see an approximate last seen value. This keeps stalkers away but makes it possible to understand whether a person is reachable over Telegram. There are four possible approximate values:</p>
                <ul>
                    <li><strong>Last seen recently</strong> — covers anything between 1 second and 2-3 days</li>
                    <li><strong>Last seen within a week</strong> — between 2-3 and seven days</li>
                    <li><strong>Last seen within a month</strong> — between 6-7 days and a month</li>
                    <li><strong>Last seen long time ago</strong> — more than a month (this is also always shown to blocked users)</li>
                </ul>
                <h4><a class="anchor" name="q-who-can-see-me-online" href="#q-who-can-see-me-online"><i class="anchor-icon"></i></a>Q: Who can see me ‘online’?</h4>
                <p>The <a href="#q-can-i-hide-my-last-seen-time">last seen</a> rules apply to your online status as well. People can only see you online if you&#39;re sharing your last seen status with them. There is one exception to this: people will be able to see you online for a brief period when you send them a message in a one-on-one chat or in a group where you both are members.</p>
                <h4><a class="anchor" name="q-can-i-make-calls-or-video-calls-via-telegram" href="#q-can-i-make-calls-or-video-calls-via-telegram"><i class="anchor-icon"></i></a>Q: Can I make calls or video calls via Telegram?</h4>
                <p>We specialize in sending messages, large media and files — and we do this better than anyone out there. There are still many things that we can revolutionize in messaging. And messaging is obviously trending at the moment, so our focus remains in that area for now.</p>
                <h4><a class="anchor" name="q-how-can-i-use-emoticons-in-telegram-on-my-ios-device" href="#q-how-can-i-use-emoticons-in-telegram-on-my-ios-device"><i class="anchor-icon"></i></a>Q: How can I use emoticons in Telegram on my iOS device?</h4>
                <p>We support emoji emoticons. Simply enable the Emoji keyboard in your iOS device‘s Settings (General – Keyboards – Add New Keyboard… – Emoji). Then switch to that keyboard whenever you’re out of words.</p>
                <h3><a class="anchor" name="groups-supergroups-and-channels" href="#groups-supergroups-and-channels"><i class="anchor-icon"></i></a>Groups, Supergroups, and Channels</h3>
                <h4><a class="anchor" name="q-why-are-supergroups-cool" href="#q-why-are-supergroups-cool"><i class="anchor-icon"></i></a>Q: Why are supergroups cool?</h4>
                <p>Telegram Supergroups can have up to <strong>5000 members</strong> each and are extremely powerful communication tools. Here are a few key features that make them stand out in the messaging world:  </p>
                <p><strong>Unified history</strong><br>Edit your messages after posting, delete them so that they disappear for everyone.</p>
                <p><strong>Cross-platform availability</strong><br>Access your messages anytime, from any number of your mobile or desktop devices.</p>
                <p><strong>Instant search</strong><br>Find the message you&#39;re looking for, even among millions.</p>
                <p><strong>Replies, mentions, hashtags</strong><br>Easily trace a conversation and keep communication efficient, no matter the group size.</p>
                <p><strong>Smart notifications</strong><br>Mute the group to get notifications only when people mention you or reply to your messages.</p>
                <p><strong>File sharing</strong><br>Send and receive files of any type, up to 1,5 GB in size each, access them instantly on your other devices.</p>
                <p><strong>Customization via bots</strong><br>Create custom tools for any specific needs using our <a href="https://core.telegram.org/bots">Bot API</a> and <a href="https://core.telegram.org/bots/inline">Inline Bots</a>.</p>
                <h4><a class="anchor" name="q-what-39s-the-difference-between-groups-supergroups-and-channel" href="#q-what-39s-the-difference-between-groups-supergroups-and-channel"><i class="anchor-icon"></i></a>Q: What&#39;s the difference between groups, supergroups, and channels?</h4>
                <p>Telegram <strong>groups</strong> are ideal for sharing stuff with friends and family or collaboration in small teams, they can have up to 200 members and by default everyone can add new people and edit the name and group photo.</p>
                <p>If your group grows to a very large community, you can upgrade it into a more centralized <strong>supergroup</strong>. <a href="/blog/supergroups">Supergroups</a> can have up to 5000 members and have a unified history, deleted messages will disappear for everyone.</p>
                <p><strong>Channels</strong> are a tool for broadcasting <em>public</em> messages to large audiences. In fact, a channel can have an unlimited number of members. When you post in a channel, the message is signed with the channel&#39;s name and photo and not your own.</p>
                <blockquote>
                    <p><a href="/faq_channels">Read more about channels in the Channels FAQ »</a></p>
                </blockquote>
                <h4><a class="anchor" name="q-how-do-i-create-a-group" href="#q-how-do-i-create-a-group"><i class="anchor-icon"></i></a>Q: How do I create a group?</h4>
                <p><em>iOS:</em> Start a new message (tap the icon in the top right corner in Chats). Then ‘New Group’.<br><em>Android:</em> Tap the circular pencil icon in the chats list. Then ‘New Group’.<br><em>Windows Phone:</em> Tap the “+” button on the bottom bar. Then ‘New Group’.</p>
                <h4><a class="anchor" name="q-can-i-assign-administrators" href="#q-can-i-assign-administrators"><i class="anchor-icon"></i></a>Q: Can I assign administrators?</h4>
                <p>Telegram groups are democratic by design. Everyone can invite new members and change the group‘s name and photo, which is ideal for small bands of friends or coworkers. For larger communities that need more administration, we’ve introduced a special restricted mode. </p>
                <p>In the restricted mode, only administrators can add new people and change the name and photo of the group. Admins also have the power to remove other members from the group.</p>
                <p><em>iOS:</em> Go to Group Info (tap the photo in the top right corner on the group‘s chat screen) — Edit — Add Admins. Disable ’All Members Are Admins&#39; and appoint admins from the list.<br><em>Android:</em> Go to Group Info (tap the name in the header) — … (in the top right corner) — Set Admins. Disable ‘All Members Are Admins’ and appoint admins from the list.<br><em>WP:</em> Go to Group Info (tap the name in the header) — … (in the bottom right corner) — Set Admins. Disable ‘All Members Are Admins’ and appoint people from the list.</p>
                <h4><a class="anchor" name="q-how-do-i-add-more-members-what-39s-an-invite-link" href="#q-how-do-i-add-more-members-what-39s-an-invite-link"><i class="anchor-icon"></i></a>Q: How do I add more members? What&#39;s an invite link?</h4>
                <p>You can add your contacts, or using search by <a href="#q-what-are-usernames-how-do-i-get-one">username</a>.</p>
                <p>It is easy to migrate existing groups to Telegram by sending people an <strong>invite link</strong>. To create an invite link, go to Group Info — Add Member — Invite to Group via Link.</p>
                <p>Anyone who has Telegram installed will be able to join your group by following this link. If you choose to revoke the link, it will stop working immediately.</p>
                <blockquote>
                    <p><a href="/blog/invite-links">Read more about invite links in our blog »</a></p>
                </blockquote>
                <h3><a class="anchor" name="usernames-and-telegram-me" href="#usernames-and-telegram-me"><i class="anchor-icon"></i></a>Usernames and telegram.me</h3>
                <h4><a class="anchor" name="q-what-are-usernames-how-do-i-get-one" href="#q-what-are-usernames-how-do-i-get-one"><i class="anchor-icon"></i></a>Q: What are usernames? How do I get one?</h4>
                <p>You can set up a <strong>public</strong> username on Telegram. It then becomes possible for other users to find you by that username — you will appear in contacts search under ‘global results’. Please note that people who find you will be able to send you messages, even if they don&#39;t know your number. If you are not comfortable with this, we advise against setting up a username in Telegram.</p>
                <p>You can set up a username in Settings and use the universal search box in the chats list to search for chats, messages, and usernames.</p>
                <h4><a class="anchor" name="q-how-does-telegram-me-work" href="#q-how-does-telegram-me-work"><i class="anchor-icon"></i></a>Q: How does telegram.me work?</h4>
                <p>Once you&#39;ve set up a username, you can give people a <a href="https://telegram.me/YourUsernameHere">telegram.me/YourUsernameHere</a> link. Opening that link on their phone will automatically fire up their Telegram app and open a chat with you. You can share username links with friends, write them on business cards or put them up on your website.</p>
                <p>This way people can contact you on Telegram without knowing your phone number.</p>
                <h4><a class="anchor" name="q-what-can-i-use-as-my-username" href="#q-what-can-i-use-as-my-username"><i class="anchor-icon"></i></a>Q: What can I use as my username?</h4>
                <p>You can use a-z, 0-9 and underscores. Usernames are case-insensitive, but Telegram will store your capitalization preferences (e.g. Telegram and TeleGram is the same user). The username must be at least five characters long.</p>
                <h4><a class="anchor" name="q-do-i-need-a-username" href="#q-do-i-need-a-username"><i class="anchor-icon"></i></a>Q: Do I need a username?</h4>
                <p>You don‘t have to get one. Remember that Telegram usernames are public and choosing a username on Telegram makes it possible for people to find you in global search and send you messages even if they don’t have your number. If you are not comfortable with this, we advise against setting up a username.</p>
                <h4><a class="anchor" name="q-if-someone-finds-me-by-username-messages-and-i-reply-will-they" href="#q-if-someone-finds-me-by-username-messages-and-i-reply-will-they"><i class="anchor-icon"></i></a>Q: If someone finds me by username, messages and I reply — will they know my number?</h4>
                <p>No. Neither party will see another‘s phone number. This is similar to the case when you message a person who you’ve met in a Telegram group.</p>
                <p>There is one exception to this: just as in the case of all Telegram messages, if <strong>you</strong> have somebody‘s number saved as a contact and you send them a message, your number also becomes visible to them. Just like with SMS. This happens regardless of how you open the conversation with that person — via the contacts menu, global search by username, telegram.me link, or from a group’s members page.</p>
                <h4><a class="anchor" name="q-how-do-i-delete-my-username" href="#q-how-do-i-delete-my-username"><i class="anchor-icon"></i></a>Q: How do I delete my username?</h4>
                <p>Go to Settings and save an empty username. This will remove your username; people will no longer be able to find you via search. This will not affect existing conversations.</p>
                <h4><a class="anchor" name="q-what-do-i-do-if-my-username-is-taken" href="#q-what-do-i-do-if-my-username-is-taken"><i class="anchor-icon"></i></a>Q: What do I do if my username is taken?</h4>
                <p>Telegram usernames are distributed on a first come — first serve basis.</p>
                <p>We understand that certain usernames are part of an online identity for some of us. If your desired username is already taken, we will be happy to help you acquire it for your account or channel, provided that you have that same username on at least <strong>two</strong> of these services: Facebook, Twitter, Instagram.</p>
                <p>Due to the fact that one account can register multiple bot and channel usernames, we reserve the right to recall usernames assigned to unused bots and channels, as well as openly squatted usernames.</p>
                <p>Please contact our in-app Support if you have more questions (Settings — Ask a question). Notice that we rely on <a href="https://core.telegram.org/tsi">volunteers</a> support in Telegram (so please be nice). Ping us on <a href="https://twitter.com/telegram">Twitter</a> if you get no response within a day or so.</p>
                <h3><a class="anchor" name="bots" href="#bots"><i class="anchor-icon"></i></a>Bots</h3>
                <blockquote>
                    <p>If you&#39;re a developer, you may find our <a href="https://core.telegram.org/bots/faq">Bots FAQ</a> more useful.</p>
                </blockquote>
                <h4><a class="anchor" name="q-how-do-i-create-a-bot" href="#q-how-do-i-create-a-bot"><i class="anchor-icon"></i></a>Q: How do I create a bot?</h4>
                <p>Creating Telegram bots is super-easy, but you will need at least some skills in computer programming. If you‘re sure you’re up to it, our <a href="https://core.telegram.org/bots"><strong>Introduction for Developers</strong></a> is a good place to start.</p>
                <p>Unfortunately, there are no out-of-the-box ways to create a working bot if you are not a developer. But we‘re sure you’ll soon find plenty of bots created by other people to play with.</p>
                <h4><a class="anchor" name="q-a-bot-is-sending-me-messages-how-do-i-make-it-stop" href="#q-a-bot-is-sending-me-messages-how-do-i-make-it-stop"><i class="anchor-icon"></i></a>Q: A bot is sending me messages, how do I make it stop?</h4>
                <p>If you don‘t want a bot to send you messages, feel free to block it – same as you would block a human user. Some Telegram clients have a ’Stop Bot‘ button right in the bot’s profile.</p>
                <p>That said, most bot developers offer commands that silence the bot, check its <em>/help</em> for clues.</p>
                <h4><a class="anchor" name="q-are-bots-safe" href="#q-are-bots-safe"><i class="anchor-icon"></i></a>Q: Are bots safe?</h4>
                <p>Yes. Bots are no different from human users that you meet in groups for example. They can see your public name and profile pictures, and they can see messages you send to them, that&#39;s it. They <strong>don&#39;t</strong> see your phone number (unless you decide to give it to them yourself).</p>
                <p>Naturally, any bot should be treated as a stranger — don&#39;t give them your passwords, Telegram codes or bank account numbers, even if they ask nicely. Also, be careful when opening files sent by bots, same as you would deal with ordinary humans. Example: If a bot sent us a file called <em>OpenMe.exe</em>, we probably wouldn&#39;t open it.</p>
                <h4><a class="anchor" name="q-if-i-add-a-bot-to-my-group-can-it-read-my-messages" href="#q-if-i-add-a-bot-to-my-group-can-it-read-my-messages"><i class="anchor-icon"></i></a>Q: If I add a bot to my group, can it read my messages?</h4>
                <p>Bots can work in two modes when you add them to groups. By default, bots only see messages that are meant for them. In this case, you‘ll see ’has no access to messages&#39; in the group members list next to the bot.</p>
                <p>Some bots need more information to work, so developers may disable privacy mode. In this case, the bot will see all messages sent to the group, and you will see ‘has access to messages’ in the members list next to the bot.</p>
                <p><a href="https://core.telegram.org/bots#privacy-mode">Learn more about privacy mode for bots »</a></p>
                <p>If your group contains very sensitive information, maybe it‘s better to avoid adding bots you don’t trust 100%.</p>
                <h4><a class="anchor" name="q-do-you-have-official-bots" href="#q-do-you-have-official-bots"><i class="anchor-icon"></i></a>Q: Do you have official bots?</h4>
                <p>Sorry, we don‘t have any official bots and don’t build them ourselves. We‘ve mentioned a few bots created by the platform’s beta testers in our <a href="/blog/bot-revolution">blog</a>. Maybe you&#39;ll like them?</p>
                <h4><a class="anchor" name="q-where-can-i-find-more-bots" href="#q-where-can-i-find-more-bots"><i class="anchor-icon"></i></a>Q: Where can I find more bots?</h4>
                <p>There is no official store at the moment, so you‘ll have to ask your friends or search the web for now. We’re pretty sure you&#39;ll find some bots to play with.</p>
                <h3><a class="anchor" name="security" href="#security"><i class="anchor-icon"></i></a>Security</h3>
                <blockquote>
                    <p>If you are an advanced user, you may find our <a href="https://core.telegram.org/techfaq">FAQ for the Technically Inclined</a> useful as well.</p>
                </blockquote>
                <h4><a class="anchor" name="q-how-secure-is-telegram" href="#q-how-secure-is-telegram"><i class="anchor-icon"></i></a>Q: How secure is Telegram?</h4>
                <p>Telegram is more secure than mass market messengers like WhatsApp and Line. We are based on the MTProto protocol (see <a href="https://core.telegram.org/mtproto">description</a> and <a href="https://core.telegram.org/techfaq">advanced FAQ</a>), built upon time-tested algorithms to make security compatible with high-speed delivery and reliability on weak connections. We are continuously working with the community to improve the security of our protocol and clients.</p>
                <h4><a class="anchor" name="q-what-if-im-more-paranoid-than-your-regular-user" href="#q-what-if-im-more-paranoid-than-your-regular-user"><i class="anchor-icon"></i></a>Q: What if I’m more paranoid than your regular user?</h4>
                <p>We&#39;ve got you covered. Telegram’s special <a href="#secret-chats">secret chats</a> use end-to-end encryption, leave no trace on our servers, support self-destructing messages and don’t allow forwarding. On top of this, secret chats are not part of the Telegram cloud and can only be accessed on their devices of origin.</p>
                <h4><a class="anchor" name="q-so-how-do-you-encrypt-data" href="#q-so-how-do-you-encrypt-data"><i class="anchor-icon"></i></a>Q: So how do you encrypt data?</h4>
                <p>We support two layers of secure encryption. <a href="https://core.telegram.org/mtproto">Server-client encryption</a> is used in Cloud Chats (private and group chats), Secret Chats use an additional layer of <a href="https://core.telegram.org/api/end-to-end">client-client encryption</a>. All data, regardless of type, is encrypted in the same way — be it text, media or files.</p>
                <p>Our encryption is based on 256-bit symmetric AES encryption, 2048-bit RSA encryption, and Diffie–Hellman secure key exchange. You can find more info in the <a href="https://core.telegram.org/techfaq">Advanced FAQ</a>.</p>
                <h4><a class="anchor" name="q-why-should-i-trust-you" href="#q-why-should-i-trust-you"><i class="anchor-icon"></i></a>Q: Why should I trust you?</h4>
                <p>Telegram is open, anyone can check our <a href="/apps#source-code">source code</a>, <a href="//core.telegram.org/mtproto">protocol</a> and <a href="//core.telegram.org/api">API</a>, see how everything works and make an informed decision. In fact, we welcome security experts to audit our system and will appreciate any feedback (<a href="mailto:security@telegram.org">security@telegram.org</a>). We offer bounties for successfully identified vulnerabilities.</p>
                <p>On top of that, Telegram&#39;s primary focus is not to <a href="#q-how-are-you-going-to-make-money-out-of-this">bring a profit</a>, so commercial interests will never interfere with our mission.</p>
                <blockquote>
                    <p>See also: <a href="/press">articles about Telegram</a></p>
                </blockquote>
                <h4><a class="anchor" name="q-do-i-need-to-trust-telegram-for-this-to-be-secure" href="#q-do-i-need-to-trust-telegram-for-this-to-be-secure"><i class="anchor-icon"></i></a>Q: Do I need to trust Telegram for this to be secure?</h4>
                <p>When it comes to <a href="#secret-chats">secret chats</a>, you don‘t — just make sure that the visualized key of your secret chat matches the one in your friend’s secret chat settings. <a href="faq#q-whats-this-encryption-key-39-thing">More about this below</a>.</p>
                <h4><a class="anchor" name="q-what-if-my-hacker-friend-says-they-could-decipher-telegram-mes" href="#q-what-if-my-hacker-friend-says-they-could-decipher-telegram-mes"><i class="anchor-icon"></i></a>Q: What if my hacker friend says they could decipher Telegram messages?</h4>
                <p>Anyone who claims that Telegram messages can be deciphered is welcome to prove that claim in our competition and <a href="https://telegram.org/blog/cryptocontest">win $300,000</a>. You can check out the <a href="https://core.telegram.org/contest300K">Cracking Contest Description</a> to learn more.</p>
                <p>Comments on Telegram&#39;s security outside the scope of the contest are welcome at <a href="mailto:security@telegram.org">security@telegram.org</a>. We offer bounties for successfully identified vulnerabilities in our apps and protocol.</p>
                <h4><a class="anchor" name="q-can-telegram-protect-me-against-everything" href="#q-can-telegram-protect-me-against-everything"><i class="anchor-icon"></i></a>Q: Can Telegram protect me against everything?</h4>
                <p>Telegram can help when it comes to data transfer and secure communication. This means that all data (including media and files) that you send and receive via Telegram cannot be deciphered when intercepted by your ISP, network administrator or other third parties.</p>
                <p>But please remember that we cannot protect you from your own mother if she takes your unlocked phone without a passcode. Or from your IT-department if they access your computer at work. Or from any other people that get physical or <a href="http://en.wikipedia.org/wiki/Superuser">root</a> access to your phones or computers running Telegram.</p>
                <p>If you have reasons to worry about your personal security, we strongly recommend using only <a href="#secret-chats">Secret Chats</a> in official or at least verifiable open-source apps for sensitive information, preferably with a <a href="#q-how-do-self-destructing-messages-work">self-destruct timer</a>. We also recommend enabling 2-Step Verification and setting up a strong passcode to lock your app, you will find both options in Settings — Privacy and Security.</p>
                <h4><a class="anchor" name="q-how-does-2-step-verification-work" href="#q-how-does-2-step-verification-work"><i class="anchor-icon"></i></a>Q: How does 2-Step Verification work?</h4>
                <p>Logging in with an SMS code is an industry standard in messaging, but if you&#39;re looking for more security or have reasons to doubt your mobile carrier or government, we recommend protecting your cloud chats with an additional password.</p>
                <p>You can do this in <strong>Settings – Privacy and Security – 2-Step Verification</strong>. Once enabled, you will need both an SMS code and a password to log in. You can also set up a recovery email address that will help regain access, should you forget your password. If you do so, please remember that it&#39;s important that the recovery email account is also protected with a strong password and 2-Step Verification when possible.</p>
                <p><a href="https://xkcd.com/936/">Check this out</a> for tips on creating a strong password that is easy to remember.</p>
                <h4><a class="anchor" name="q-why-can-jailbroken-and-rooted-devices-be-dangerous" href="#q-why-can-jailbroken-and-rooted-devices-be-dangerous"><i class="anchor-icon"></i></a>Q: Why can jailbroken and rooted devices be dangerous?</h4>
                <p>Using a rooted or jailbroken device makes it easier for a potential attacker to gain full administrative control over your device — <a href="http://en.wikipedia.org/wiki/Superuser">root access</a>.</p>
                <p>A user with root access can easily bypass security features built into the operating system, read process memory or access restricted areas, such as the <a href="http://developer.android.com/guide/topics/data/data-storage.html#filesInternal">internal storage</a>. Once an attacker has root access, any efforts to mitigate threats become futile. No application can be called safe under these circumstances, no matter how strong the encryption.</p>
                <h3><a class="anchor" name="secret-chats" href="#secret-chats"><i class="anchor-icon"></i></a>Secret Chats</h3>
                <h4><a class="anchor" name="q-how-are-secret-chats-different" href="#q-how-are-secret-chats-different"><i class="anchor-icon"></i></a>Q: How are secret chats different?</h4>
                <p>Secret chats are meant for people who want more secrecy than the average fella. All messages in secret chats use end-to-end encryption. This means only you and the recipient can read those messages — nobody else can decipher them, including us here at Telegram (<a href="#q-can-telegram-protect-me-against-everything">more on this here</a>). Messages cannot be forwarded from secret chats. And when you delete messages on your side of the conversation, the app on the other side of the secret chat will be ordered to delete them as well.</p>
                <p>You can order your messages, photos, videos and files to <a href="#q-how-do-self-destructing-messages-work">self-destruct</a> in a set amount of time after they have been read or opened by the recipient. The message will then disappear from both your and your friend&#39;s devices.</p>
                <p>All secret chats in Telegram are device-specific and are not part of the Telegram cloud. This means you can only access messages in a secret chat from their device of origin. They are safe for as long as your device is safe in your pocket.</p>
                <h4><a class="anchor" name="q-how-do-i-start-a-secret-chat" href="#q-how-do-i-start-a-secret-chat"><i class="anchor-icon"></i></a>Q: How do I start a secret chat?</h4>
                <p><em>iOS:</em> Start a new message (tap the icon in the top-right corner in Messages). Then ‘New secret chat’.<br><em>Android:</em> Swipe right to open the menu, then ‘New secret chat’.<br><em>WP:</em> Tap + in the chats list, then ‘New secret chat’.</p>
                <p>Remember that Telegram secret chats are device-specific. If you start a secret chat with a friend on one of your devices, this chat will only be available on that device. If you log out, you will lose all your secret chats. You can create as many different secret chats with the same contact as you like.</p>
                <h4><a class="anchor" name="q-how-do-self-destructing-messages-work" href="#q-how-do-self-destructing-messages-work"><i class="anchor-icon"></i></a>Q: How do self-destructing messages work?</h4>
                <p>The Self-Destruct Timer is available for Secret Chats only. To set the timer, simply tap the clock icon (in the input field on iOS, top bar on Android, chat info page on WP), and then Set Self-Destruct Timer to the desired time limit. The clock starts ticking the moment the message is displayed on the recipient&#39;s screen (gets two green checks). As soon as the time runs out, the message disappears from <strong>both</strong> devices.</p>
                <p>Photos sent with short self-destruct timers (&lt; 1 minute) can only be viewed while you&#39;re holding your finger on them — and we will try to notify both parties whenever a screenshot is taken.</p>
                <p>Please note that the timer only applies to messages that were sent <strong>after</strong> the timer was set. It has no effect on earlier messages.</p>
                <h4><a class="anchor" name="q-can-i-be-certain-that-my-conversation-partner-doesn-39t-take-a" href="#q-can-i-be-certain-that-my-conversation-partner-doesn-39t-take-a"><i class="anchor-icon"></i></a>Q: Can I be certain that my conversation partner doesn&#39;t take a screenshot?</h4>
                <p>Unfortunately, there is no bulletproof way of detecting screenshots on certain systems (most notably, some Android and Windows Phone devices). We will make every effort to alert you about screenshots taken in your Secret Chats, but it may still be possible to bypass such notifications and take screenshots silently. We advise to share sensitive information only with people you trust. After all, nobody can stop a person from taking a picture of their screen with a different device or an old school camera.</p>
                <h4><a class="anchor" name="q-whats-this-encryption-key-39-thing" href="#q-whats-this-encryption-key-39-thing"><i class="anchor-icon"></i></a>Q: What‘s this ’Encryption Key&#39; thing?</h4>
                <p>When a secret chat is created, the participating devices exchange encryption keys using the so-called <a href="http://en.wikipedia.org/wiki/Diffie%E2%80%93Hellman_key_exchange">Diffie-Hellman key exchange</a>. After the secure end-to-end connection has been established, we generate a picture that visualizes the encryption key for your chat. You can then compare this image with the one your friend has — if the two images are the same, you can be sure that the secret chat is secure, and no <a href="http://en.wikipedia.org/wiki/Man-in-the-middle_attack">man-in-the-middle attack</a> can succeed.</p>
                <p>Newer versions of Telegram apps will show a larger picture along with a textual representation of the key (this is not the key itself, of course!) when both participants are using an updated app.</p>
                <p>Always compare visualizations using a channel that is known to be secure — it&#39;s safest if you do this in person, in an offline meeting with the conversation partner.</p>
                <h4><a class="anchor" name="q-why-not-just-make-all-chats-secret" href="#q-why-not-just-make-all-chats-secret"><i class="anchor-icon"></i></a>Q: Why not just make all chats ‘secret’?</h4>
                <p>All Telegram messages are always securely encrypted. Messages in Secret Chats use <strong>client-client</strong> encryption, while Cloud Chats use <strong>client-server/server-client</strong> encryption and are stored encrypted in the Telegram Cloud (more <a href="/privacy#2-storing-data">here</a>). This enables your cloud messages to be both <a href="#q-do-you-process-data-requests">secure</a> and immediately accessible from any of your devices – even if you lose your device altogether.</p>
                <p>The problem of restoring access to your chat history on a newly connected device (e.g. when you lose your phone) does not have an elegant solution in the end-to-end encryption paradigm. At the same time, reliable backups are an essential feature for any mass-market messenger. To solve this problem, some applications (like Whatsapp and Viber) allow <a href="https://www.eff.org/deeplinks/2016/10/where-whatsapp-went-wrong-effs-four-biggest-security-concerns">unencrypted backups</a> that put their users&#39; privacy at risk – even if they do not enable backups themselves. Other apps ignore the need for backups altogether and fade into oblivion before ever reaching a million users.</p>
                <p>We opted for a third approach by offering two distinct types of chats. Telegram disables default system backups and provides all users with an integrated security-focused backup solution in the form of Cloud Chats. Meanwhile, the separate entity of Secret Chats gives you full control over the data you do not want to be stored.</p>
                <p>This allows Telegram to be widely adopted in broad circles, not just by activists and dissidents so that the simple fact of using Telegram does not mark users as targets for heightened surveillance in certain countries. We are convinced that the separation of conversations into Cloud and Secret chats represents the most secure solution currently possible for a massively popular messaging application.</p>
                <h3><a class="anchor" name="deeper-questions" href="#deeper-questions"><i class="anchor-icon"></i></a>Deeper questions</h3>
                <h4><a class="anchor" name="q-why-not-open-source-everything" href="#q-why-not-open-source-everything"><i class="anchor-icon"></i></a>Q: Why not open source everything?</h4>
                <p>All code will be released eventually. We started with the most useful parts — a well-documented API that allows developers to build new Telegram apps, and open source clients that can be verified by security specialists.</p>
                <h4><a class="anchor" name="q-can-i-run-telegram-using-my-own-server" href="#q-can-i-run-telegram-using-my-own-server"><i class="anchor-icon"></i></a>Q: Can I run Telegram using my own server?</h4>
                <p>Our architecture does not support federation yet. Telegram is a unified cloud service, so creating forks where two users might end up on two different Telegram clouds is unacceptable. To enable you to run your own Telegram server while retaining both speed and security is a task in itself. At the moment, we are undecided on whether or not Telegram should go in this direction.</p>
                <h4><a class="anchor" name="q-can-i-use-the-telegram-api" href="#q-can-i-use-the-telegram-api"><i class="anchor-icon"></i></a>Q: Can I use the Telegram API?</h4>
                <p>Yes. Developers for all platforms are welcome to use our <a href="//core.telegram.org/mtproto">protocol</a>, <a href="//core.telegram.org/api">API</a> and even <a href="https://telegram.org/apps#source-code">source code</a>. Check out the <a href="//core.telegram.org/api#getting-started">Getting started</a> section of the docs.</p>
                <blockquote>
                    <p>Don&#39;t forget about our <a href="https://core.telegram.org/bots">Bot API</a> that lets you build cool stuff on our platform.</p>
                </blockquote>
                <h4><a class="anchor" name="q-do-you-have-a-privacy-policy" href="#q-do-you-have-a-privacy-policy"><i class="anchor-icon"></i></a>Q: Do you have a Privacy Policy?</h4>
                <p>Sure. Check <a href="/privacy">this</a> out.</p>
                <h4><a class="anchor" name="q-why-do-you-have-two-apps-in-the-mac-app-store" href="#q-why-do-you-have-two-apps-in-the-mac-app-store"><i class="anchor-icon"></i></a>Q: Why do you have two apps in the Mac App store?</h4>
                <p>One is our <a href="/dl/osx">native OSX app</a>, the other is the OSX version of our multi-platform client— <a href="https://desktop.telegram.org">Telegram Desktop</a>. Both apps are official. Both started out as unofficial applications by two different developers and vary in design and functionality.</p>
                <p><a href="https://desktop.telegram.org">Telegram Desktop</a> is currently the more <strong>stable</strong> version. It is optimized for photo and document sharing, as well as sending long text messages.</p>
                <p>The <a href="/dl/osx">OSX app</a> features native OSX design and supports secret chats.</p>
                <h4><a class="anchor" name="q-can-i-translate-telegram" href="#q-can-i-translate-telegram"><i class="anchor-icon"></i></a>Q: Can I translate Telegram?</h4>
                <p>Telegram is officially available in English, Spanish, German, Dutch, Italian, Arabic, Portuguese and Korean on most platforms.</p>
                <p>We are gradually expanding the list of official languages built into the apps, but there are other options as well. Telegram apps support <strong>external language packs</strong>. The .xml files for the Android app and Localizable.strings files for iOS can be downloaded from <a href="https://www.transifex.com/organization/telegram/">this Transifex page</a>. Of course, you can also change the language files in any way you like and thus create your own personal Telegram localization.</p>
                <p>To apply an external language pack, send (or receive) the file via Telegram (attached as ‘file’), download it, then tap on it to see the menu (on Android: tap on … in the upper right corner of the doc bubble) then select ‘Apply localization file’. You will see a language selection menu with the language from the file as one of the options. Yes, this <em>is</em> damn tricky, we&#39;ll simplify the process in the next versions.</p>
                <h4><a class="anchor" name="q-can-i-help" href="#q-can-i-help"><i class="anchor-icon"></i></a>Q: Can I help?</h4>
                <p>Yes, we are always looking for volunteers to help us with user support, since we are not a commercial organization. If you would be interested in answering questions about Telegram to users from your country, contact our auditions account.</p>
                <p>Before you apply, please check out the <a href="https://core.telegram.org/tsi">Telegram Support Initiative</a>.</p>
                <h3><a class="anchor" name="your-account" href="#your-account"><i class="anchor-icon"></i></a>Your Account</h3>
                <h4><a class="anchor" name="q-how-do-i-log-out" href="#q-how-do-i-log-out"><i class="anchor-icon"></i></a>Q: How do I log out?</h4>
                <p>Remember, that you can use Telegram on as many devices at the same time, as you like. If you log out, you don&#39;t lose your cloud messages. However, you <strong>will lose</strong> all your <strong>Secret Chats</strong> and <strong>all messages</strong> inside them when you log out. Note that logging out doesn‘t trigger remote deletion of your secret chat messages on your partner’s device — to do that, choose ‘clear history’ first.</p>
                <p><em>iOS</em>: Go to Settings, then Edit, then Log out.<br><em>Android, Windows Phone</em>: Go to Settings, then Log out.</p>
                <h4><a class="anchor" name="q-how-do-i-change-my-phone-number" href="#q-how-do-i-change-my-phone-number"><i class="anchor-icon"></i></a>Q: How do I change my phone number?</h4>
                <p>You can change your number in Telegram and keep <strong>everything</strong>, including all your contacts, messages, and media from the Telegram cloud, as well as all your Secret Chats on all devices.</p>
                <p><strong>Important:</strong> Your mutual contacts (people in your contacts who also have your number) will get your new number added to your contact in their address book unless you have blocked them in Telegram. This makes changing numbers even easier.</p>
                <p>To change your number, go to Settings, then tap on your phone number (just above the username), then ‘Change Number’. If you already have a different Telegram account on the target number, you&#39;ll need to <a href="#q-how-do-i-delete-my-account">delete</a> that account first.</p>
                <h4><a class="anchor" name="q-how-do-i-delete-my-account" href="#q-how-do-i-delete-my-account"><i class="anchor-icon"></i></a>Q: How do I delete my account?</h4>
                <p>If you would like to delete your account, you can do this on the <a href="https://telegram.org/deactivate">deactivation page</a>. Deleting your account permanently removes all your <strong>messages</strong>, <strong>groups</strong> and <strong>contacts</strong>. This action must be confirmed via your Telegram account and cannot be undone.</p>
                <blockquote>
                    <p>We recommend using a non-mobile browser for this process.<br>Note that you&#39;ll receive the <strong>code</strong> via <strong>Telegram</strong>, not SMS.</p>
                </blockquote>
                <h4><a class="anchor" name="q-what-happens-if-i-delete-my-account" href="#q-what-happens-if-i-delete-my-account"><i class="anchor-icon"></i></a>Q: What happens if I delete my account?</h4>
                <p>As was just mentioned above, all your data will be flushed from our system: all messages, groups, and contacts associated with your account will be deleted. That said, your contacts will still be able to chat in the groups that you have created, and they will still have <em>their</em> copy of the messages you sent them. So if you want to send messages that can vanish without a trace, try using our <a href="#q-how-do-self-destructing-messages-work">self-destruct timer</a> instead.</p>
                <p>Your supergroups, bots, and channels will be deleted <strong>completely</strong>, together with all the messages for all users. All usernames associated with your account, including bot and channel usernames, will be freed.</p>
                <p>Termination of a Telegram account is irreversible. If you sign up again, you will appear as a new user and will not get your history, contacts or groups back. People, who have your phone number in their contacts, will be notified. The new user will be displayed as a separate conversation in their messages list and their conversation history with this new user will be empty.</p>
                <h4><a class="anchor" name="q-how-does-account-self-destruction-work" href="#q-how-does-account-self-destruction-work"><i class="anchor-icon"></i></a>Q: How does account self-destruction work?</h4>
                <p>Telegram is not a commercial organization, and we value our disk space greatly. If you stop using Telegram and do not log in for at least six months, your account will be deleted along with all messages, media, contacts and every other piece of data you store in the Telegram cloud. You can change the exact period after which your inactive account will self-destruct in Settings.</p>
                <p>This feature was introduced on November 19, 2014. Since the default self-destruct setting for Telegram accounts is six months, accounts that have been last active before November 19, 2014, self-destructed on <strong>May 19, 2015</strong>.</p>
                <h4><a class="anchor" name="q-my-phone-was-stolen-what-do-i-do" href="#q-my-phone-was-stolen-what-do-i-do"><i class="anchor-icon"></i></a>Q: My phone was stolen. What do I do?</h4>
                <p>First of all, sorry about your phone. Unfortunately, the phone number is the only way for us to identify a Telegram user at the moment. We don‘t collect additional information about you, so whoever has the number, has the account. This means we can’t help you unless you have access either to the phone number or to Telegram itself on any of your devices.</p>
                <h6><a class="anchor" name="i-have-access-to-telegram-on-another-device" href="#i-have-access-to-telegram-on-another-device"><i class="anchor-icon"></i></a>I have access to Telegram on another device</h6>
                <ol>
                    <li>Go to Telegram Settings — Privacy and Security and turn on Two-Step Verification. This way the phone number alone will not be enough to log in to your account.</li>
                    <li>Go to Settings — Privacy and Security — Active Sessions and terminate your Telegram session on the old device. Whoever has your phone will not be able to log in again, since they don&#39;t know your password.</li>
                    <li>Contact your phone provider, so that they block your old SIM and issue a new one with your number.</li>
                    <li>If you decide to switch to a new phone number, don&#39;t forget to go to Settings, tap on your phone number and change your Telegram number to the new one.</li>
                </ol>
                <h6><a class="anchor" name="i-don-39t-have-access-to-telegram-on-any-other-devices" href="#i-don-39t-have-access-to-telegram-on-any-other-devices"><i class="anchor-icon"></i></a>I don&#39;t have access to Telegram on any other devices</h6>
                <ol>
                    <li>First and foremost, you need to contact your phone provider, so that they block your old SIM and issue a new one with your number.</li>
                    <li>Wait till you receive your new SIM with the old number, log in to Telegram, then go to Settings — Privacy and Security — Active Sessions and terminate your Telegram session on the old device.</li>
                </ol>
                <h6><a class="anchor" name="removing-sensitive-data" href="#removing-sensitive-data"><i class="anchor-icon"></i></a>Removing sensitive data</h6>
                <p>Common thieves usually throw out the SIM card immediately (the phone is harder to locate this way), then wipe the devices and sell them, so there isn&#39;t much risk for the data in case of regular petty theft. But if you have reasons to worry about the data on the device and are unable to <a href="#i-have-access-to-telegram-on-another-device">log out the other device</a>, it is best that you wipe it remotely. You can read more about it here: <a href="http://support.apple.com/kb/PH2701">Apple iOS</a>, <a href="https://www.google.com/android/devicemanager">Android</a>. Unfortunately, this requires you to have prepared in advance for this scenario.</p>
                <p>You can <a href="#q-how-do-i-delete-my-account">delete your Telegram account</a> if you are logged in on at least one of your other devices (mobile or desktop). Note that inactive Telegram accounts self-destruct automatically after a period of time — 6 months being the default setting.</p>
                <hr>
                <h3><a class="anchor" name="troubleshooting" href="#troubleshooting"><i class="anchor-icon"></i></a>Troubleshooting</h3>
                <h4><a class="anchor" name="login-and-sms" href="#login-and-sms"><i class="anchor-icon"></i></a>Login and SMS</h4>
                <p>Please make sure you are entering your mobile phone number in the international format. I.e.: +(country code)(city or carrier code)(your number).</p>
                <p>If you are having registration or login problems, please contact us using <a href="https://telegram.org/support">this form</a>.</p>
                <h4><a class="anchor" name="notification-problems" href="#notification-problems"><i class="anchor-icon"></i></a>Notification problems</h4>
                <p><em>iOS:</em></p>
                <ol>
                    <li>Go to Telegram Settings — Notifications and Sounds, make sure that notifications are ON in Telegram.</li>
                    <li>Check that notifications are ON in phone Settings.</li>
                    <li>Check, whether contact or group is <em>muted</em>.</li>
                    <li>Shut down Telegram (go to home screen, double tap home button, kill Telegram (swipe upwards), then go to phone settings, set the alert style for Telegram to NONE. Relaunch Telegram, go to phone settings, set alert style back to banners.</li>
                </ol>
                <p><em>Android:</em></p>
                <p>We currently have two types of notifications on Android: GCM and our own custom notification service that is independent from Google. Note that Google notifications (GCM) just won‘t work properly on some Android devices. The Telegram notification service is reliable but requires additional battery resources. It doesn’t and shouldn&#39;t take much, though, so please report all drastic battery-draining cases immediately.</p>
                <ol>
                    <li>Go to Telegram Settings — Notifications and Sounds, make sure that notifications are ON.</li>
                    <li>Check, whether contact or group is <em>muted</em>.</li>
                    <li>If the Telegram <em>Notifications Service</em> is disabled, make sure <a href="https://play.google.com/store/apps/details?id=com.google.android.gms">Google Play Services</a> are installed on your phone.</li>
                    <li>If the Telegram <em>Notifications Service</em> is enabled and your phone uses some battery saving software, make sure that Telegram is whitelisted in that application.</li>
                </ol>
                <blockquote>
                    <p>NOTE: <strong>Huawei</strong> and <strong>Xiaomi</strong> devices have evil task killer services that interfere with the Telegram notification service. For our notifications to work, you need to add Telegram to allowed apps in those devices&#39; security settings. Huawei: Phone Manager App &gt; Protected Apps &gt; Add Telegram to the list. Xiaomi: Services &gt; Security &gt; Permissions &gt; Autostart, find Telegram and enable autostart.</p>
                </blockquote>
                <p><em>Windows Phone:</em></p>
                <ol>
                    <li>Go to Telegram Settings — Notifications and Sounds, make sure that notifications are ON in Telegram.</li>
                    <li>Check that notifications are ON in phone Settings.</li>
                    <li>Check, whether contact or group is muted.</li>
                    <li>Try Settings &gt; Notifications &gt; Reset notifications.</li>
                    <li>Shut down Telegram (hold back button, kill Telegram (swipe downwards), then go to phone settings, notifications and actions, deactivate Telegram. Relaunch Telegram, go to phone settings, Notifications and Actions, set alert back to ON.</li>
                </ol>
                <h4><a class="anchor" name="problems-with-contacts" href="#problems-with-contacts"><i class="anchor-icon"></i></a>Problems with contacts</h4>
                <p>If you know your friends have Telegram, but you can&#39;t see them — or they appear as numbers instead of names.</p>
                <p><em>iOS:</em></p>
                <ol>
                    <li>Force quit the app (double tap home button, then swipe up on Telegram), then relaunch and check if it helped.</li>
                    <li>If that doesn&#39;t help, temporarily change the name of the contact in phone contacts (add a few symbols, then change back again).</li>
                    <li>If that doesn’t work, re-login: Settings – Edit – Log Out. Remember that logging out kills all your Secret Chats. Then log in again.</li>
                </ol>
                <p><em>Android:</em></p>
                <ol>
                    <li>Make sure you are using the latest version of the app.</li>
                    <li>Relaunch the app (by terminating it from processes list and launching again).</li>
                    <li>Temporarily change the name of the contact in phone contacts (add a few symbols, then change back again).</li>
                    <li>If that didn&#39;t help, try to re-login.</li>
                </ol>
                <p><em>Windows Phone:</em></p>
                <ol>
                    <li>Make sure you are using the latest version of the app.</li>
                    <li>Relaunch the app (hold back button, swipe downwards to kill Telegram, then launch again).</li>
                    <li>Temporarily change the name of the contact in phone contacts (add a few symbols, then change back again).</li>
                    <li>If that didn&#39;t help, try to re-login.</li>
                </ol>
                <h4><a class="anchor" name="deleting-contacts-on-android-and-wp" href="#deleting-contacts-on-android-and-wp"><i class="anchor-icon"></i></a>Deleting contacts on Android and WP</h4>
                <p>To delete a contact, open a chat with the person, tap on their profile photo in the top area of the chat screen, then:</p>
                <p><em>Android:</em> Tap on ‘…’ in the top right corner — ‘Delete’.<br><em>WindowsPhone:</em> Tap on the pen icon — ‘Delete’.</p>
                <p>If you want to delete the contact completely, make sure you also delete them from your phone contacts. Telegram stays in sync and will add the contact back if you don&#39;t.</p>
                <h4><a class="anchor" name="where-did-my-secret-chat-messages-go" href="#where-did-my-secret-chat-messages-go"><i class="anchor-icon"></i></a>Where did my Secret Chat messages go?</h4>
                <p>Secret Chats are established between the two devices they were created on. This means that all those messages are not available in the cloud and cannot be accessed on other devices.</p>
                <p>Moreover, Secret Chats are also tied to your current login session on the device. If you log out and in again, you will lose all your Secret Chats.</p>
                <h4><a class="anchor" name="can-39t-send-messages-to-non-contacts" href="#can-39t-send-messages-to-non-contacts"><i class="anchor-icon"></i></a>Can&#39;t send messages to non-contacts</h4>
                <p>When users report unwanted messages from a Telegram account, we apply a limit: Reported accounts can only send messages to people who have their number saved as a contact.</p>
                <p>This means that if you randomly contact people you don&#39;t know and send them annoying messages, you may lose the ability to do so in the future.</p>
                <p>If you think that this limit was applied to your account wrongly, please visit <a href="/faq_spam">this page</a>.</p>
                <hr>
                <h3><a class="anchor" name="telegram-support" href="#telegram-support"><i class="anchor-icon"></i></a>Telegram Support</h3>
                <p>If you have any other questions, please contact Telegram Support (in Telegram go to Settings — Ask a question). Note that we rely on volunteers for support.</p>
                <p>If you can&#39;t log in to your account, please use <a href="https://telegram.org/support">this form</a>.</p>
                <h3><a class="anchor" name="twitter" href="#twitter"><i class="anchor-icon"></i></a>Twitter?</h3>
                <p>Yep. Follow us! <a href="https://twitter.com/telegram"><strong>@telegram</strong></a><br>Our twitter account in Spanish: <a href="https://twitter.com/telegram_es">@telegram_es</a><br>In Italian: <a href="https://twitter.com/telegram_it">@telegram_it</a><br>In Korean: <a href="https://twitter.com/telegram_kr">@Telegram_kr</a><br>For users from Brazil: <a href="https://twitter.com/telegram_br">@Telegram_br</a><br>Our Arabic-speaking users may find <a href="https://twitter.com/telegram_arabic">@telegram_arabic</a> more interesting.</p>
                <h3><a class="anchor" name="smstelegram-login-help-on-twitter" href="#smstelegram-login-help-on-twitter"><i class="anchor-icon"></i></a>@SmsTelegram, login help on Twitter</h3>
                <p>We have a special account that can help you with login problems, <a href="https://twitter.com/smstelegram"><strong>@smstelegram</strong></a>. This account is official. Don&#39;t be afraid to DM it the number you use for Telegram, we need this info to investigate issues.</p>
                <p>Be careful, we don&#39;t have any other support accounts on any social media platforms.</p>
                <h3><a class="anchor" name="facebook" href="#facebook"><i class="anchor-icon"></i></a>Facebook?</h3>
                <p>Facebook seems to have taken down our page for no apparent reason several months ago. Well, who cares, we weren‘t using it much anyway. (This was the address, in case you’re curious: <a href="https://www.facebook.com/tlgrm"><a href="https://www.facebook.com/tlgrm">https://www.facebook.com/tlgrm</a></a>). Right now, if anyone on Facebook is telling you they&#39;re us, they are <strong>not</strong>.</p>
            </div>
        </div>
    </section><!-- /.main-containt -->